### ISSUE TITLE
Comentários

### ISSUE THREAD

**Issue by renatoOliveira25** [f3lip3-almeida/API-Zool-gico-31-01-2024#1]
Pedro, a classe Ave.ts ficou sem comentários, faça os comentários para essa classe também.
Nos próximos projetos, utilize o mesmo estilo de comentário para os atributos também.
Outra observação, é interessante você colocar um comentário para a classe também, assim fica mais fácil pra alguém que pegar o seu código para dar manutenção entender o contexto, por exemplo:
```typescript
/** 
 * Representa um habitat no zoológico, onde os animais vivem. 
 */ 
export class Habitat {
```

Lembre-se que você pode usar o ChatGPT para te ajudar a comentar as classes.

**Comment by renatoOliveira25** [comment]
Vou deixar um exemplo de uma classe comentada.

```typescript
import { Animal } from "./Animal";

/**
 * Representa um habitat no zoológico, onde os animais vivem.
 */
export class Habitat {

    /**
     * O nome do habitat.
     */
    private nome: string;

    /**
     * A lista de animais que habitam este habitat.
     */
    private listaAnimais: Array<Animal>;

    /**
     * Cria uma nova instância de Habitat.
     * 
     * @param _nome O nome do habitat.
     * @param _listaAnimais A lista de animais que habitam o habitat.
     */
    constructor(_nome: string, _listaAnimais: Array<Animal>) {
        this.nome = _nome;
        this.listaAnimais = _listaAnimais;
    }

    /**
     * Obtém o nome do habitat.
     * 
     * @returns O nome do habitat.
     */
    public getNome(): string {
        return this.nome;
    }

    /**
     * Define o nome do habitat.
     * 
     * @param _nome O nome a ser atribuído ao habitat.
     */
    public setNome(_nome: string): void {
        this.nome = _nome;
    }

    /**
     * Obtém a lista de animais do habitat.
     * 
     * @returns A lista de animais do habitat.
     */
    public getListaAnimais(): Array<Animal> {
        return this.listaAnimais;
    }

    /**
     * Define a lista de animais do habitat.
     * 
     * @param _listaAnimais A lista de animais a ser atribuída ao habitat.
     */
    public setListaAnimais(_listaAnimais: Array<Animal>): void {
        this.listaAnimais = _listaAnimais;
    }
}

```

**Comment by f3lip3-almeida** [comment]
Já terminei professor a Issues obrigado por avisar, agora a classe ave está comentada e vou sumir um commit dela:
-----------------------------------------------------------------------------------------------------------------------------------
 
/** 
 * Representa uma classe para aves, que são animais com penas e geralmente capazes de voar.
 */ 
import { Animal } from "./Animal";

export class Ave extends Animal {
    private envergadura: number; // Envergadura da ave

    /**
     * Construtor da classe Ave.
     * @param _nome O nome da ave.
     * @param _especie A espécie da ave.
     * @param _idade A idade da ave.
     * @param _genero O gênero da ave.
     * @param _envergadura A envergadura da ave.
     */
    constructor(_nome: string,
        _especie:string,
        _idade: number,
        _genero: string,
        _envergadura: number){
            super(_nome, _idade, _genero);
            this.envergadura = _envergadura;
        }

    /**
     * Retorna a envergadura da ave.
     * @returns A envergadura da ave.
     */
    public getEnvergadura(): number {
        return this.envergadura;
    }

    /**
     * Define a envergadura da ave.
     * @param envergadura A nova envergadura para a ave.
     */
    public setEnvergaruda(envergadura:number):void{
        this.envergadura = envergadura;
    }
} 

------------------------------------------------
ISSUES CONCLUIDO: 16/02/2024
